### ISSUE TITLE
Nix support ?

### ISSUE THREAD

**Issue by AkechiShiro** [Athena-OS/athena-cyber-hub#2]
Is Nix support planned for this tool ?

**Comment by D3vil0p3r** [comment]
Currently I don't have the time to manage it. Feel free to create one of it.

**Comment by AkechiShiro** [comment]
I'll see if I can package this but it doesn't look simple and has a lot of features

**Comment by AkechiShiro** [comment]
Do you have any recommendation on what I could use as a version since there are no release tag on the repo ?

I will reopen this issue if I need help, but for now I will close it.

**Comment by D3vil0p3r** [comment]
> Do you have any recommendation on what I could use as a version since there are no release tag on the repo ?
> 
> I will reopen this issue if I need help, but for now I will close it.

You can use the latest commit.
